language: node_js
node_js:
  - "5"
  - "4"
before_script:
  - psql -U postgres -c 'DROP DATABASE IF EXISTS piratedb_test;'
  - psql -U postgres -c 'CREATE DATABASE piratedb_test;'
  - psql -U postgres -c "CREATE USER piratedb WITH PASSWORD 'piratedb';"
  - psql -U postgres -c 'GRANT ALL PRIVILEGES ON DATABASE piratedb_test to piratedb;'
env:
  - CXX=g++-4.8
addons:
  postgresql: "9.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - postgresql
