
const action = "administration"

// Update member
export const UPDATE_MEMBER_PENDING = `${action}.UPDATE_MEMBER_PENDING`
export const UPDATE_MEMBER_FULFILLED = `${action}.UPDATE_MEMBER_FULFILLED`
export const UPDATE_MEMBER_REJECTED = `${action}.UPDATE_MEMBER_REJECTED`

// Create user for member
export const CREATE_USER_FOR_MEMBER_PENDING = `${action}.CREATE_USER_FOR_MEMBER_PENDING`
export const CREATE_USER_FOR_MEMBER_FULFILLED = `${action}.CREATE_USER_FOR_MEMBER_FULFILLED`
export const CREATE_USER_FOR_MEMBER_REJECTED = `${action}.CREATE_USER_FOR_MEMBER_REJECTED`

// Toggle user enabled/disabled
export const TOGGLE_USER_ENABLED_PENDING = `${action}.TOGGLE_USER_ENABLED_PENDING`
export const TOGGLE_USER_ENABLED_FULFILLED = `${action}.TOGGLE_USER_ENABLED_FULFILLED`
export const TOGGLE_USER_ENABLED_REJECTED = `${action}.TOGGLE_USER_ENABLED_REJECTED`
