
const action = "forgottenPassword."

export const FORGOTTEN_PASSWORD_INITIAL = action + "FORGOTTEN_PASSWORD_INITIAL"
export const FORGOTTEN_PASSWORD_PENDING = action + "FORGOTTEN_PASSWORD_PENDING"
export const FORGOTTEN_PASSWORD_FULFILLED = action + "FORGOTTEN_PASSWORD_FULFILLED"
export const FORGOTTEN_PASSWORD_REJECTED = action + "FORGOTTEN_PASSWORD_REJECTED"