
const action = "forgottenPasswordChange."

export const FORGOTTEN_PASSWORD_CHANGE_INITIAL = action + "FORGOTTEN_PASSWORD_CHANGE_INITIAL"
export const FORGOTTEN_PASSWORD_CHANGE_PENDING = action + "FORGOTTEN_PASSWORD_CHANGE_PENDING"
export const FORGOTTEN_PASSWORD_CHANGE_FULFILLED = action + "FORGOTTEN_PASSWORD_CHANGE_FULFILLED"
export const FORGOTTEN_PASSWORD_CHANGE_REJECTED = action + "FORGOTTEN_PASSWORD_CHANGE_REJECTED"