#!/bin/bash

# select your major version number, i.e. 4, 5, 6, 7, 8, 9...
series=7

# determine the latest version file name
echo "Determining the URL for the latest package..."
url_prefix=https://nodejs.org/dist/latest-v$series.x/
version_name=$(wget -qO - $url_prefix | sed -n -re 's/.+(node-v[0-9]+\.[0-9]+\.[0-9]+\.tar\.gz).+$/\1/p')
echo "Found $version_name"

# create a temp folder and download the package
echo "Downloading package $url_prefix$version_name"
src=$(mktemp -d) && cd $src
wget -N $url_prefix$version_name
tar xzvf $version_name && cd node-v*

# configure and build node using fakeroot and checkinstall
./configure
sudo fakeroot checkinstall -y --install=no --pkgname=nodejs --pkgversion $(echo $(pwd) | sed -n -re's/.+node-v(.+)$/\1/p') make -j$(($(nproc)+1)) install

# install the package
sudo dpkg -i node_*

