- name: install ufw
  apt: name=ufw

- name: open port 22
  ufw: rule=allow port=22 proto=tcp

- name: open port 80
  ufw: rule=allow port=80 proto=tcp

- name: open port 443
  ufw: rule=allow port=443 proto=tcp

- ufw:
    state: enabled
    policy: deny